# Generated by Django 6.0.3 on 2026-03-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_enquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
